### ISSUE TITLE
Immediate Error Loading File without loading window

### ISSUE THREAD

**Issue by gcannestro1** [RDastgh1/MEAnalyzer#7]
When trying to load a .h5 file exported with MCS DataManager, I get the "error loading file" status in the top right corner. The sample .hf file works as it should. There is no pop-up window showing loading, it goes straight to the error message. I am using Windows 10 OS.
I am trying to load the file under "No Layout" as the MEA 24 well plate is not on the dropdown list.

**Comment by Xinyi1222** [comment]
I have the same problem. It should be the file exported as the Spike Time Stamps. But the problem is I do not have the selection of choosing ST or not.

**Comment by RDastgh1** [comment]
I believe in these cases the issue was that your hf files only contained voltages, and not spike time stamps. If using MCS files please make sure that you have detected spikes and that you have exported them as events. MEAnaluzyzer only analyzes spike trains, it does not do spike detection or spike sorting.
